# Generated by Django 6.0.4 on 2026-04-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('ocassion', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('school', 'В школу'), ('no_reason', 'Без повода'), ('other', 'Другой повод')], max_length=50, verbose_name='Повод')),
                ('photo', models.ImageField(upload_to='bouquet_photo/', verbose_name='Фото')),
                ('meaning', models.TextField(verbose_name='Значение букета')),
                ('composistion', models.TextField(verbose_name='Состав')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('position', models.CharField(choices=[('florist', 'Флорист'), ('Courier', 'Курьер')], max_length=20, verbose_name='Должность')),
                ('condition', models.CharField(choices=[('work', 'Работает'), ('sick', 'Больничный'), ('vacation', 'В отпуске')], default='work', max_length=20, verbose_name='Состояние')),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True, verbose_name='Номер заказа')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.CharField(max_length=50, verbose_name='Время доставки')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('delivered', 'Производится доставка'), ('delivered', 'Доставлен')], default='new', max_length=20, verbose_name='Статус')),
                ('amount', models.IntegerField(verbose_name='Сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bouquet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouquet_orders', to='bot_app.bouquet', verbose_name='Букет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bot_app.tguser', verbose_name='Пользователь')),
            ],
        ),
    ]
