# Generated by Django 6.0.4 on 2026-04-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('florist', 'Флорист'), ('courier', 'Курьер')], max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_delivery', 'Производится доставка'), ('delivered', 'Доставлен')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
