# Generated by Django 6.0.4 on 2026-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_alter_employee_position_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь Telegram', 'verbose_name_plural': 'Пользователи Telegram'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
