# Generated by Django 6.0.4 on 2026-04-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_alter_bouquet_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Клиент в Telegram', 'verbose_name_plural': 'Клиенты в Telegram'},
        ),
        migrations.RenameField(
            model_name='bouquet',
            old_name='composistion',
            new_name='composition',
        ),
        migrations.RenameField(
            model_name='bouquet',
            old_name='ocassion',
            new_name='occasion',
        ),
    ]
