# Generated by Django 6.0.4 on 2026-04-23 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='consultation',
            name='budget',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='event',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Повод'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='final_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='bot_app.order', verbose_name='Итоговый заказ'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='initial_bouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_initial', to='bot_app.bouquet', verbose_name='Изначальный букет'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('in_progress', 'В работе'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
