# Generated by Django 6.0.4 on 2026-04-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_remove_consultation_completed_at_consultation_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('florist', 'Флорист'), ('courier', 'Курьер'), ('director', 'Руководитель')], max_length=20, verbose_name='Должность'),
        ),
    ]
