# Generated by Django 6.0.4 on 2026-04-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('discount', models.IntegerField(verbose_name='Скидка (в рублях)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Дуйствует до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
