# Generated by Django 5.2.8 on 2026-04-25 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='bot_app.employee', verbose_name='Курьер'),
        ),
    ]
